const paymentDetailsActionTypes = {
  FETCH_PAYMENT_DETAILS_START: "FETCH_PAYMENT_DETAILS_START",
  FETCH_PAYMENT_DETAILS_SUCCESS: "FETCH_PAYMENT_DETAILS_SUCCESS",
  FETCH_PAYMENT_DETAILS_FAIL: "FETCH_PAYMENT_DETAILS_FAIL",

};

export default paymentDetailsActionTypes;
